# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G -XX:TieredStopAtLevel=1
org.gradle.parallel=true

# Mod properties
mod_name=Item Frame Anywhere
mod_description=Place item frames (almost) anywhere
mod_version=1.0.0
mod_license=MIT
maven_group=me.imbanana
mod_id=item_frame_anywhere
archives_name=ItemFrameAnywhere
enabled_platforms=fabric,neoforge

# Architectury properties
loom_version=1.17-SNAPSHOT
architectury_plugin_version=3.5-SNAPSHOT

# Minecraft properties
minecraft_version=26.2

# Dependencies
fabric_loader_version=0.19.3
fabric_api_version=0.155.2+26.2
neoforge_version=26.2.0.25-beta
java_version=25

# Publishing
modrinth_id = xxx
fabric_loader_version_range=>=0.19.0
fabric_game_version_range=~26.2
fabric_game_versions=26.2
neoforge_loader_version_range=[26.2,)
neoforge_game_version_range=[26.2,)
neoforge_game_versions=26.2